title: OER FAQ
url: "https://faq.openoregon.org"

# Build settings
markdown: kramdown
remote_theme: sandbergja/jekyll-library-diy@main
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

baseurl: '/'
